version: 2.1

orbs:
  kurtosis-docs-checker: kurtosis-tech/docs-checker@0.2.9
  node: circleci/node@5.2.0

executors:
  ubuntu_vm:
    machine:
      image: ubuntu-2404:current

jobs:
  run_starlark:
    executor: ubuntu_vm
    steps:

      # Set up Kurtosis
      - run: |
          echo "deb [trusted=yes] https://apt.fury.io/kurtosis-tech/ /" | sudo tee /etc/apt/sources.list.d/kurtosis.list
          sudo apt update
          sudo apt install kurtosis-cli
      - run: |
          git clone https://github.com/kurtosis-tech/redis-package.git .

      # We don't send metrics to avoid polluting our logs
      - run: kurtosis config init dont-send-metrics

      - run: kurtosis engine restart

      - run: |
          kurtosis run ${PWD}
  
workflows:
  build:
    jobs:
      # -- PR check jobs ------------------------------------------
      - node/install:
          node-version: "20.18.1"
          filters:
            branches:
              ignore:
                - main
      - kurtosis-docs-checker/check-docs:
          requires:
            - node/install
          should-check-changelog: false
          markdown-link-check-config-json: | 
            {
              "ignorePatterns": [
                {
                  "pattern": "/run.gif"
                }                
              ]
            }
          filters:
            branches:
              ignore:
                - main
      - run_starlark:
          filters:
            branches:
              ignore:
                - main